# Generated by Django 4.2.16 on 2024-12-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_customuser_date_joined_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'usuario'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='users_images/default-avatar.png', upload_to='users_images'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=15, unique=True, verbose_name='nombre de usuario'),
        ),
    ]
